DEVICE_PATH := device/lge/mlv5
PRODUCT_PLATFORM := mt6755

TARGET_BOARD_PLATFORM := mt6755_mlv5
TARGET_SLSI_VARIANT := bsp
TARGET_SOC := mt6755
TARGET_BOOTLOADER_BOARD_NAME := mt6755
TARGET_BOARD_PLATFORM_GPU := mali-t860
TARGET_OTA_ASSERT_DEVICE := mlv5
TARGET_NO_BOOTLOADER := true

# CPU
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

# HIDL
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/hidl/goldfish/manifest.xml
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/hidl/goldfish/compatibility_matrix.xml

# PROPERTIES

TARGET_SYSTEM_PROP += $(DEVICE_PATH)/prop/system.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/prop/product.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/prop/vendor.prop

# KERNEL

TARGET_NO_KERNEL := true
#TARGET_KERNEL_SOURCE := kernel/lge/mlv5
#TARGET_KERNEL_CONFIG := lv5_global_com_defconfig
#TARGET_KERNEL_CLANG_COMPILE := false

BOARD_KERNEL_BASE := 0x00100000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_IMAGE_NAME := Image

# SYSTEM
# FIXME: lv5_global_com_defconfig should use 64 bit binder
TARGET_USES_64_BIT_BINDER := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
AB_OTA_UPDATER := false
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_AVB_ENABLE := false

# FIXME: values below are not correct for this device

BOARD_KERNEL_OFFSET          := 0x00008000
BOARD_KERNEL_RAMDISK_OFFSET  := 0x01000000
BOARD_KERNEL_TAGS_OFFSET     := 0x00000100

BOARD_BOOTIMAGE_PARTITION_SIZE := 57671680 # 56 MB
BOARD_DTBOIMG_PARTITION_SIZE := 8388608 # 8 MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67633152 # 66 MB
BOARD_CACHEIMAGE_PARTITION_SIZE := 629145600 # 614 MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5976883200 # 5 GB
BOARD_VENDORIMAGE_PARTITION_SIZE := 1153433600 # 1 GB
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 650117120 # 634 MB

BOARD_USERDATAIMAGE_PARTITION_SIZE := 119126601728

BOARD_FLASH_BLOCK_SIZE := 4096
